# -*- coding: utf-8 -*-
"""vehicles_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvokkMobs2Cfo8fFhiRIyQJMvPpl82i4
"""

import requests as rq
from pyspark.sql import SparkSession
from pyspark.sql.types import IntegerType, StringType, DataType, DateType
from pyspark.sql.functions import col, lower, trim, upper,md5, concat_ws
import os
from dotenv import load_dotenv

spark = SparkSession.builder \
    .appName("VehicleDataPipeline") \
    .getOrCreate()

def ingestion():
    load_dotenv(dotenv_path=".env")

    api_url = os.getenv("api_key")
    req = rq.get(api_url)

    response = req.json()
    wanted_cols= ["id","version","vehicle_type",
                "public_vehicle_number","status","vehicle_model","vehicle_model_year",
                "vehicle_color","vehicle_fuel_source","company_name","address",
                "city","state","record_id","last_valid_date"]

    filtered_data = [{k: row[k] for k in wanted_cols if k in row} for row in response]
    df = spark.createDataFrame(filtered_data)
    print(df)
    df.write.mode("overwrite").parquet("./vehicles_data_bronze")
    return df

df = ingestion()

def transformation(input_df):
      df = input_df.drop_duplicates()
      df_cleaned = df.dropna("all")
      str_cols = ['record_id',
          'address', 'city', 'company_name',
          'state', 'status', 'vehicle_color', 'vehicle_fuel_source',
          'vehicle_model', 'vehicle_type'
      ]
      int_cols = [ 'vehicle_model_year','public_vehicle_number']

      date_cols = ['last_valid_date']

      for col_name in str_cols:
          clean_col_name = col_name.strip().lower()
          df_cleaned = df_cleaned.withColumn(clean_col_name, upper(trim(col(col_name))).cast(StringType()))

      for col_name in int_cols:
          clean_col_name = col_name.strip().lower()
          df_cleaned = df_cleaned.withColumn(clean_col_name, col(col_name).cast(IntegerType()))

      for col_name in date_cols:
          clean_col_name = col_name.strip().lower()
          df_cleaned = df_cleaned.withColumn(col_name, col(col_name).cast(DateType()))
          null_counts = [{i:df.filter(df[i].isNull()).count()for i in df_cleaned.columns}]

      df_cleaned = df_cleaned.fillna({"vehicle_color": "UNKNOWN", "vehicle_model": "UNKNOWN", "city": "UNKNOWN", "state": "UNKNOWN"})
      df_cleaned = df_cleaned.fillna({"vehicle_model_year": 0})
      df_cleaned.write.mode("overwrite").parquet("./vehicles_data_silver")
      return df_cleaned

df_cleaned = transformation(df)

def load(cld_df):

    dim_vehicle = cld_df.select(
        "public_vehicle_number", "vehicle_type", "vehicle_model",
        "vehicle_model_year", "vehicle_color", "vehicle_fuel_source"
    ).dropDuplicates(["public_vehicle_number"])

    cld_df=cld_df.withColumn(
        "company_hash_id",
        md5(concat_ws("", col("company_name"), col("address"))))

    dim_company = cld_df.select(
        "company_hash_id","company_name", "address", "city", "state"
    ).dropDuplicates(["company_name"])

    fact_vehicles = cld_df.select(
        "record_id", "public_vehicle_number", "company_hash_id",
        "last_valid_date", "status")
    dim_vehicle.write.mode("overwrite").parquet("./dim_vehicle")
    dim_company.write.mode("overwrite").parquet("./dim_company")
    fact_vehicles.write.mode("overwrite").parquet("./fact_vehicles")

    return cld_df

load(df_cleaned)

spark.read.parquet("./fact_vehicles").createOrReplaceTempView("fact_vehicles")
spark.read.parquet("./dim_company").createOrReplaceTempView("dim_company")
spark.read.parquet("./dim_vehicle").createOrReplaceTempView("dim_vehicle")




combined = spark.sql("""
SELECT
    f.record_id,
    f.public_vehicle_number,
    c.company_hash_id,
    c.company_name,
    c.address,
    c.city,
    c.state,
    f.last_valid_date,
    f.status,
    v.vehicle_type,
    v.vehicle_model,
    v.vehicle_model_year,
    v.vehicle_color

FROM
    fact_vehicles f
JOIN
    dim_company c ON f.company_hash_id = c.company_hash_id
JOIN
    dim_vehicle v ON f.public_vehicle_number = v.public_vehicle_number
""")

combined.createOrReplaceTempView("combined")

# @title
count_of_vehicle_type = spark.sql("""
with ranked_rides as(
SELECT
    record_id,
    public_vehicle_number,
    company_name,
    vehicle_model,
    vehicle_model_year,
    vehicle_color,
    address,
    COUNT(*) OVER (PARTITION BY vehicle_type) AS total_count,
    ROW_NUMBER() OVER (PARTITION BY vehicle_type ORDER BY vehicle_model_year DESC) AS rn
FROM
    combined
)
SELECT
        total_count,
        vehicle_model,
        vehicle_model_year
    FROM ranked_rides
    WHERE rn = 1
    ORDER BY vehicle_model_year DESC
""")
count_of_vehicle_type.createOrReplaceTempView("count_of_vehicle_type")

print(count_of_vehicle_type.show(5,truncate=False))

